# Generated by Django 5.1.1 on 2024-10-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_adminstats_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="payement_key",
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
