# Generated by Django 5.1.1 on 2024-10-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_alter_reservation_payement_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="qr_code",
            field=models.TextField(default=""),
        ),
    ]
