# Generated by Django 5.1.1 on 2024-10-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0005_remove_reservation_offer_reservation_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="image",
            field=models.ImageField(default="offers/default.jpg", upload_to="offers/"),
        ),
    ]
