# Generated by Django 5.1.1 on 2024-10-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0006_offer_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="decription",
            field=models.TextField(default=""),
        ),
    ]
