name: Github Actions for Django

on: 
    pull_request:
        branches: ['master','main']
        paths-ignore: ['docs/**']

    push:
        branches: ['master','main']
        paths-ignore: ['docs/**']

concurrency:
    group: ${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 2
            matrix:
                python-version: [3.11, 3.12] 

                django-version: [3.2, 4.0, 4.1]

        steps:
            - name: Checkout Code Repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }} # Utiliser la version de la matrice

            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

    deploy:
        runs-on: ubuntu-latest
        name: Deploy Django Application
        needs: build
        steps:
            - name: Checkout Code Repository
              uses: actions/checkout@v2
    
            - name: Install Heroku CLI
              run: curl https://cli-assets.heroku.com/install.sh | sh
    
            - name: Set Heroku Buildpacks
              run: heroku buildpacks:set heroku/python -a ${{ secrets.HEROKU_APP_NAME }}
    
            - name: Verify `requirements.txt` and `Procfile`
              run: |
                echo "Checking requirements.txt and Procfile"
                ls -l requirements.txt 
                ls -l Procfile
    
            - name: Deploy to Heroku
              uses: akhileshns/heroku-deploy@v3.12.12
              with:
                heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
                heroku_email: cassamb97@gmail.com
                branch: main
                dontuseforce: 1
    
            - name: Run Django Migrations on Heroku
              run: |
                heroku run python manage.py migrate -a ${{ secrets.HEROKU_APP_NAME }}
              env:
                HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
